#pragma warning disable OPENAI001

using Azure.Identity;
using Microsoft.Extensions.Options;
using OpenAI.Responses;
using System.ClientModel.Primitives;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using VideoSceneSearch.Models;

namespace VideoSceneSearch.Services;

public interface IFoundryAgentClient
{
    Task<string> SearchScenesAsync(string query, Dictionary<string, string> availableVideos, CancellationToken cancellationToken = default);
}

/// <summary>
/// Azure AI Foundry ホステッドエージェントを OpenAI Responses API で呼び出すクライアント。
/// Microsoft Entra ID (DefaultAzureCredential) を使用してキーレス認証を行います。
/// </summary>
public class FoundryAgentClient : IFoundryAgentClient
{
    private readonly ResponsesClient _responsesClient;
    private readonly AzureAIFoundrySettings _settings;
    private readonly IAzureSearchService _searchService;
    private readonly ILogger<FoundryAgentClient> _logger;

    // Structured Output schema — agent picks resultIds from the retrieved context.
    // timestamps, videoId, and other metadata are resolved from AI Search results
    // by the client, not generated by the agent.
    private static readonly BinaryData _responseSchema = BinaryData.FromString("""
        {
          "type": "object",
          "properties": {
            "scenes": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "resultId": { "type": "string" },
                  "evidence": { "type": "string" }
                },
                "required": ["resultId", "evidence"],
                "additionalProperties": false
              }
            }
          },
          "required": ["scenes"],
          "additionalProperties": false
        }
        """);

    // Agent response parsing helpers.
    private sealed record AgentPickResponse([property: JsonPropertyName("scenes")] List<AgentPick> Scenes);
    private sealed record AgentPick(
        [property: JsonPropertyName("resultId")] string ResultId,
        [property: JsonPropertyName("evidence")] string Evidence);

    public FoundryAgentClient(
        IOptions<AzureAIFoundrySettings> settings,
        IAzureSearchService searchService,
        ILogger<FoundryAgentClient> logger)
    {
        _settings = settings.Value;
        _searchService = searchService;
        _logger = logger;

        // Microsoft Entra ID を使用したキーレス認証。
        // Azure AI Foundry のスコープは https://ai.azure.com/.default を使用します。
        var tokenPolicy = new BearerTokenPolicy(
            new DefaultAzureCredential(),
            "https://ai.azure.com/.default");

        // エンドポイントは "/responses" を除いたベース URL を設定します。
        // 例: https://{resource}.services.ai.azure.com/api/projects/{project}/agents/{agent-name}/endpoint/protocols/openai
        // Azure AI Foundry のホステッドエージェント (Responses プロトコル) は api-version=v1 クエリパラメータが必須です。
        var options = new ResponsesClientOptions { Endpoint = new Uri(_settings.Endpoint) };
        options.AddPolicy(new FoundryApiVersionPolicy(), PipelinePosition.BeforeTransport);
        _responsesClient = new ResponsesClient(tokenPolicy, options);
    }

    public async Task<string> SearchScenesAsync(
        string query,
        Dictionary<string, string> availableVideos,
        CancellationToken cancellationToken = default)
    {
        _logger.LogInformation("Sending request to Foundry Hosted Agent");

        // クエリの意図を分類し、documentType フィルターを決定する
        // 人物・会話・シーン → scene / 画面・物体・瞬間 → keyframe / 不明 → null（両方）
        var docTypeFilter = ClassifyQueryIntent(query);
        _logger.LogInformation(
            "Query intent classification: {DocType}", docTypeFilter ?? "(both)");

        // Azure AI Search でシーンを事前検索し、取得したコンテキストをエージェントに渡す
        var searchResult = await _searchService.SearchAsync(
            query,
            videoIdFilter: null,
            documentTypeFilter: docTypeFilter,
            cancellationToken: cancellationToken);

        // Build message with available video context and retrieved search results
        string message;
        if (availableVideos.Count > 0)
        {
            var videoList = string.Join("\n", availableVideos.Select(v => $"- {v.Key}: {v.Value}"));
            message = $"Available videos:\n{videoList}\n\n[Azure AI Search 取得済みコンテキスト]\n{searchResult.ContextText}[/ Azure AI Search 取得済みコンテキスト]\n\nUser query: {query}";
        }
        else
        {
            message = $"[Azure AI Search 取得済みコンテキスト]\n{searchResult.ContextText}[/ Azure AI Search 取得済みコンテキスト]\n\nUser query: {query}";
        }

        var options = new CreateResponseOptions
        {
            Model = _settings.ModelDeploymentName,
            TextOptions = new ResponseTextOptions
            {
                TextFormat = ResponseTextFormat.CreateJsonSchemaFormat(
                    "scene_search_response",
                    _responseSchema,
                    null,
                    jsonSchemaIsStrict: true)
            }
        };
        options.InputItems.Add(ResponseItem.CreateUserMessageItem(message));

        var response = (await _responsesClient.CreateResponseAsync(options, cancellationToken)).Value;

        _logger.LogInformation(
            "Response from Foundry Hosted Agent: id={Id}, status={Status}, totalTokens={Tokens}",
            response.Id, response.Status, response.Usage?.TotalTokenCount);

        if (response.Status == ResponseStatus.Failed)
        {
            throw new InvalidOperationException(
                $"Agent returned failed status: {response.Error?.Code} - {response.Error?.Message}");
        }

        if (response.Status == ResponseStatus.Incomplete)
        {
            throw new InvalidOperationException(
                $"Agent response was incomplete: {response.IncompleteStatusDetails?.Reason}");
        }

        var textBuilder = new StringBuilder();
        foreach (var item in response.OutputItems)
        {
            if (item is MessageResponseItem msg)
            {
                foreach (var part in msg.Content)
                {
                    if (part.Kind == ResponseContentPartKind.OutputText)
                        textBuilder.Append(part.Text);
                    else if (part.Kind == ResponseContentPartKind.Refusal)
                        throw new InvalidOperationException($"Agent refused to answer: {part.Refusal}");
                }
            }
        }

        var agentJsonText = textBuilder.ToString();
        _logger.LogInformation("Extracted text from response ({Length} chars)", agentJsonText.Length);

        if (string.IsNullOrWhiteSpace(agentJsonText))
        {
            throw new InvalidOperationException("Agent returned no output text.");
        }

        // エージェントの picks (resultId + evidence) を検索結果ドキュメントへ解決する
        var jsonOpts = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
        var agentPicks = JsonSerializer.Deserialize<AgentPickResponse>(agentJsonText.Trim(), jsonOpts);

        double maxScore = searchResult.Documents.Count > 0
            ? searchResult.Documents.Values.Max(d => d.Score)
            : 1.0;

        var scenes = new List<SceneResult>();
        if (agentPicks?.Scenes != null)
        {
            foreach (var pick in agentPicks.Scenes)
            {
                if (string.IsNullOrEmpty(pick.ResultId) ||
                    !searchResult.Documents.TryGetValue(pick.ResultId, out var doc))
                {
                    _logger.LogWarning(
                        "Agent returned unknown resultId '{ResultId}' — skipping", pick.ResultId);
                    continue;
                }

                var title = availableVideos.TryGetValue(doc.VideoId, out var t) ? t : doc.VideoId;
                scenes.Add(new SceneResult
                {
                    VideoId     = doc.VideoId,
                    Title       = title,
                    Start       = MsToTimeString(doc.BeginMs),
                    End         = MsToTimeString(doc.EndMs),
                    Confidence  = maxScore > 0 ? doc.Score / maxScore : 0.0,
                    Evidence    = pick.Evidence,
                    Description = doc.SceneSummary,
                    Mode        = doc.DocumentType,
                });
            }
        }

        return JsonSerializer.Serialize(new SceneSearchResponse { Scenes = scenes }, jsonOpts);
    }

    /// <summary>
    /// クエリのキーワードパターンから検索対象の documentType を判定する。
    /// 統合インデックスにおける scene / keyframe の絞り込みに使用する。
    /// </summary>
    /// <returns>
    /// "scene"    — 人物・会話・シーンレベルのクエリ
    /// "keyframe" — 画面・物体・瞬間的ビジュアルのクエリ
    /// null       — 判定不能（両方を検索）
    /// </returns>
    private static string? ClassifyQueryIntent(string query)
    {
        // シーンレベル: 人物・会話・物語等
        string[] sceneKeywords =
        [
            "人物", "キャラクター", "登場", "会話", "話して", "セリフ",
            "ナレーション", "解説", "説明", "説明して", "語って",
            "誰が", "誰は", "誰を", "履歴", "シーン",
        ];

        // キーフレームレベル: 画面・物体・瞬間的ビジュアル
        string[] keyframeKeywords =
        [
            "画面", "映像", "映って", "見える", "表示", "物体",
            "アイテム", "UI", "インターフェース", "瞬間", "フレーム",
            "スクリーンショット", "テロップ", "スコア",
        ];

        int sceneScore    = sceneKeywords.Count(k => query.Contains(k, StringComparison.OrdinalIgnoreCase));
        int keyframeScore = keyframeKeywords.Count(k => query.Contains(k, StringComparison.OrdinalIgnoreCase));

        if (sceneScore > keyframeScore)
            return "scene";
        if (keyframeScore > sceneScore)
            return "keyframe";
        return null; // 同点の場合は両方を検索
    }

    /// <summary>ミリ秒を HH:MM:SS 形式の文字列へ変換する。</summary>
    private static string MsToTimeString(int ms)
    {
        var ts = TimeSpan.FromMilliseconds(ms);
        return $"{(int)ts.TotalHours:D2}:{ts.Minutes:D2}:{ts.Seconds:D2}";
    }
}

/// <summary>
/// Azure AI Foundry のホステッドエージェント (Responses プロトコル) が要求する
/// api-version=v1 クエリパラメータをすべてのリクエストに付与するパイプラインポリシー。
/// </summary>
internal sealed class FoundryApiVersionPolicy : PipelinePolicy
{
    public override void Process(PipelineMessage message, IReadOnlyList<PipelinePolicy> pipeline, int currentIndex)
    {
        AppendApiVersion(message.Request);
        ProcessNext(message, pipeline, currentIndex);
    }

    public override async ValueTask ProcessAsync(PipelineMessage message, IReadOnlyList<PipelinePolicy> pipeline, int currentIndex)
    {
        AppendApiVersion(message.Request);
        await ProcessNextAsync(message, pipeline, currentIndex);
    }

    private static void AppendApiVersion(PipelineRequest request)
    {
        // Hosted Agent refreshed preview で必須のヘッダー
        request.Headers.Set("Foundry-Features", "HostedAgents=V1Preview");

        var uriStr = request.Uri?.AbsoluteUri;
        if (uriStr is null) return;

        // api-version が未設定のリクエストのみ追加する
        if (!uriStr.Contains("api-version=", StringComparison.OrdinalIgnoreCase))
        {
            var separator = uriStr.Contains('?') ? "&" : "?";
            request.Uri = new Uri(uriStr + separator + "api-version=v1");
        }
    }
}

